language: java
#ignore install step
install: true
sudo: false
script: mvn clean install -Dmaven.javadoc.skip=true -DskipTests=false -Dgpg.skip=true
env:
  - POM_VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Brian Olsen"
      - git config --local user.email "b3t@brianolsen.us"
      - git tag "$POM_VERSION"
deploy:
  provider: releases
  api_key: "$Github_Oath_Token"
  name: "$POM_VERSION"
  body: "Release that references [osrm-text-instructions v$POM_VERSION](https://github.com/Project-OSRM/osrm-text-instructions/releases/tag/v$POM_VERSION). Release is available on [maven common repository](http://search.maven.org/#artifactdetails%7Ccom.github.brianolsen87%7Ctext-instructions%7C$POM_VERSION%7Cjar)."
  skip_cleanup: true
  on:
    branch: master